server:
  port: 3001

auth:
  token: 'U73GwtzQhF2CZG2yeNWHiQGM86AHN7Qy49eSfZ4K2vlm0eifHXfcbHdeIMMV'

twitter:
  consumer_key: 'YbR6mKLgZfnIyN5Bnqvd2rGj2'
  consumer_secret: 'r3xz96mHFZWD31uI5L96Z0ynVR1ugTFbbxf1pnyB5qjuTGM1Rj'
  access_token: '860202990937964544-UNPUChgK2idxn6m6nFKn616WEPcFuWu'
  access_token_secret: 'zFSjzaHTVjhlGgEbIGb5J8UJ1M2oTumKJDjA9mc8Q3vRf'
